version: "3.9"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - gymy-postgres:/var/lib/postgresql/data
    env_file:
     - ./.env.local

volumes:
  gymy-postgres: